import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Grid from '@mui/material/Grid';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Grid container spacing={2}>
              <Grid size={{sm: 0, md: 1, lg: 2, xl: 3}} />
              <Grid size={{sm: 12, md: 10, lg: 8, xl: 6}}>
                  {children}
              </Grid>
              <Grid size={{sm: 0, md: 1, lg: 2, xl: 3}} />
          </Grid>
      </body>
    </html>
  );
}
